### ISSUE TITLE
wifi bridging UI

### ISSUE THREAD

**Issue by hallahan** [posm/posm#127]
We need short instructions on how to turn on / off wifi bridging (@mojodna). 

This should be an action in the posm-admin UI (@hallahan).

**Comment by mojodna** [comment]
At the moment it involves "bootstrapping" `captive` vs. `bridge`:

```bash
# enable bridging (disable captive portal)
/root/scripts/bootstrap.sh bridge
```

```bash
# enable captive portal (disable bridging)
/root/scripts/bootstrap.sh captive
```

Re-using `bootstrap.sh` from posm-admin is probably a bad idea (because it overloads functionality), so we'll want to extract the functionality from `{bridge,captive}-deploy.sh` into separate scripts (w/o dependencies on variables defined in `settings`).

**Comment by mojodna** [comment]
See https://github.com/AmericanRedCross/posm-admin/pull/8

**Comment by dalekunce** [comment]
is this fixed?

**Comment by mojodna** [comment]
Not fully. It still uses the `captive` and `bridge` scripts (which have side-effects), but it does work.

**Comment by mojodna** [comment]
Done in https://github.com/posm/posm-build/commit/292320b5ff3d93b335af80f5b9078eebf996a501 and https://github.com/posm/posm-admin-ui/commit/288da367110b184d64282e7cbfc9f9be216e5c0c
