### ISSUE TITLE
way to delete ODM projects

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#286]
imagery files add up. the sony nex5 we fly takes pics that are ~13mb each. and the geoTIFFs are BIG.  i think providing a way to delete projects might be needed. maybe with an option to delete only the source images (but save the derived products). possibly use a two-step process like GitHub when deleting repositories where the user has to type the project name to confirm the delete.

alternatively just document really well the process for going in through terminal or whatever to delete the stuff manually.

what happens currently if you have project that has processed and you go in and delete only the source images? anything bad?

**Comment by mojodna** [comment]
I may have implemented an API endpoint for deletion (and/or did for the imagery API). We intentionally left the delete functionality out of the UI with the thinking that random users may find it and could run amok, but I like the idea of using GitHub's flow for inspiration.

FTR, the process for manually deleting is to delete `/opt/data/opendronemap/<uuid>/images/*` (not 100%, but it's something like that). No negative impacts other than that re-processing won't work (because there's no source imagery) and that clicking the button _may_ delete existing outputs.

**Comment by danbjoseph** [comment]
this is no longer applicable since we switched to including WebODM for access to ODM stuff
