### ISSUE TITLE
ODM project names

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#288]
what is sort order of projects? random? it doesn't seem to be based on the display name. or create date.

**Comment by danbjoseph** [comment]
being able to have duplicate names is kinda confusing for the user? though i understand this is unrelated to the system keeping track of things, so not a big deal.

![screen shot 2017-03-13 at 4 33 21 pm](https://cloud.githubusercontent.com/assets/4806884/23874430/ffbac70e-080b-11e7-81be-87f6b34e8781.png)

**Comment by mojodna** [comment]
I _think_ the sort order is by UUID (which doesn't surface in the interface, so that's confusion). It should probably sort by display name (and then fall back to UUID).

My feeling on duplicate names is that it's something that can be addressed by users, since they (you) are the ones who attach human-readable names.

**Comment by danbjoseph** [comment]
i'd be fine with both sorting by display name first and letting users worry about duplicating names on their own.
