### ISSUE TITLE
stuck loading on forms page

### ISSUE THREAD

**Issue by danbjoseph** [posm/posm#321]
fresh install using posm-build on Amazon EC2. uploaded one form and went to http://omkserver.com/omk/pages/forms/ and it is stuck on the loading icon. console shows:
```
[Vue warn]: Unknown custom element: <dialog> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
vue.js:990:11
[Vue warn]: Error when evaluating expression "formList.xforms.xform". Turn on debug mode to see stack trace.
vue.js:990:11
```

**Comment by danbjoseph** [comment]
the stuck loading sounds similar to https://github.com/posm/posm/issues/305#issuecomment-352236034 ?

**Comment by maki80** [comment]
I have the same problem, have you got to solve it?

thank you very much

**Comment by danbjoseph** [comment]
there's a workaround. not sure how. 
it's not yet fixed. but we have the resources to so in the next 3-4 months.
thanks for your patience.

**Comment by mojodna** [comment]
The underlying issue is that OMK Server makes requests to itself to fetch forms. The existing Upstart configuration assumes that a local DNS server is running (typically not the case on EC2). The diff below removes that assumption and replaces it with an explicit mapping from `posm_fqfn` (`posm.io` by default) to `eth0`'s (the default WAN interface) IP address.

@maki80 change `/etc/init/omk-server.upstart` to match the following diff:

```patch
diff --git a/kickstart/etc/omk-server.upstart b/kickstart/etc/omk-server.upstart
index c443f08..f0731b1 100644
--- a/kickstart/etc/omk-server.upstart
+++ b/kickstart/etc/omk-server.upstart
@@ -10,7 +10,7 @@ respawn
 script
   docker run \
     --rm \
-    --dns $(jq -r .posm_wlan_ip /etc/posm.json) \
+    --add-host $(jq .posm_fqdn /etc/posm.json):$(ifconfig $(jq -r .posm_wan_netif /etc/posm.json) | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1) \
     -p $(jq -r .omk_server_port /etc/posm.json):$(jq -r .omk_server_port /etc/posm.json) \
     -e PORT=$(jq -r .omk_server_port /etc/posm.json) \
     -e NODE_ENV=$(jq -r .posm_env /etc/posm.json) \
```

You'll then want to restart `omk-server` (this is the forcible way to make sure that it's fully restarted):

```bash
sudo service omk-server stop
sudo docker kill omk-server
sudo service omk-server start
```
